name: AnemllAgentHost
options:
  bundleIdPrefix: com.anemll
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.0
    ENABLE_APP_SANDBOX: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: ""
    PRODUCT_NAME: AnemllAgentHost
    INFOPLIST_FILE: AnemllAgentHost/Info.plist
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  AnemllAgentHost:
    type: application
    platform: macOS
    sources:
      - AnemllAgentHost
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.anemll.AnemllAgentHost
        CODE_SIGN_STYLE: Automatic
